POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Zbigniew",
    "number": "1234567890"
}
####
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "1234567890"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "ZAK"
}